package Google::Ads::AdWords::v201109::ApiException;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'https://adwords.google.com/api/adwords/cm/v201109' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}


use base qw(Google::Ads::AdWords::v201109::ApplicationException);
# Variety: sequence
use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %message_of :ATTR(:get<message>);
my %ApplicationException__Type_of :ATTR(:get<ApplicationException__Type>);
my %errors_of :ATTR(:get<errors>);

__PACKAGE__->_factory(
    [ qw(        message
        ApplicationException__Type
        errors

    ) ],
    {
        'message' => \%message_of,
        'ApplicationException__Type' => \%ApplicationException__Type_of,
        'errors' => \%errors_of,
    },
    {
        'message' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'ApplicationException__Type' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'errors' => 'Google::Ads::AdWords::v201109::ApiError',
    },
    {

        'message' => 'message',
        'ApplicationException__Type' => 'ApplicationException.Type',
        'errors' => 'errors',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

Google::Ads::AdWords::v201109::ApiException

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
ApiException from the namespace https://adwords.google.com/api/adwords/cm/v201109.

Exception class for holding a list of service errors. 




=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * errors




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # Google::Ads::AdWords::v201109::ApiException
   errors =>  $a_reference_to, # see Google::Ads::AdWords::v201109::ApiError
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

