package Google::Ads::AdWords::v201109::ConversionOptimizerAdGroupCriterionBids;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'https://adwords.google.com/api/adwords/cm/v201109' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}


use base qw(Google::Ads::AdWords::v201109::AdGroupCriterionBids);
# Variety: sequence
use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %AdGroupCriterionBids__Type_of :ATTR(:get<AdGroupCriterionBids__Type>);

__PACKAGE__->_factory(
    [ qw(        AdGroupCriterionBids__Type

    ) ],
    {
        'AdGroupCriterionBids__Type' => \%AdGroupCriterionBids__Type_of,
    },
    {
        'AdGroupCriterionBids__Type' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'AdGroupCriterionBids__Type' => 'AdGroupCriterionBids.Type',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

Google::Ads::AdWords::v201109::ConversionOptimizerAdGroupCriterionBids

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
ConversionOptimizerAdGroupCriterionBids from the namespace https://adwords.google.com/api/adwords/cm/v201109.

AdGroupCriterion level bids used in conversion optimizer bidding strategy. This bidding strategy does not contain any bid information at the AGC level. 




=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over



=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # Google::Ads::AdWords::v201109::ConversionOptimizerAdGroupCriterionBids
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

