package Google::Ads::AdWords::v201109::Opportunity;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'https://adwords.google.com/api/adwords/o/v201109' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %opportunityIdeas_of :ATTR(:get<opportunityIdeas>);

__PACKAGE__->_factory(
    [ qw(        opportunityIdeas

    ) ],
    {
        'opportunityIdeas' => \%opportunityIdeas_of,
    },
    {
        'opportunityIdeas' => 'Google::Ads::AdWords::v201109::OpportunityIdea',
    },
    {

        'opportunityIdeas' => 'opportunityIdeas',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

Google::Ads::AdWords::v201109::Opportunity

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
Opportunity from the namespace https://adwords.google.com/api/adwords/o/v201109.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * opportunityIdeas




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # Google::Ads::AdWords::v201109::Opportunity
   opportunityIdeas =>  $a_reference_to, # see Google::Ads::AdWords::v201109::OpportunityIdea
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

