package Google::Ads::AdWords::v201109::OpportunityAttributeType;
use strict;
use warnings;

sub get_xmlns { 'https://adwords.google.com/api/adwords/o/v201109'};

# derivation by restriction
use base qw(
    SOAP::WSDL::XSD::Typelib::Builtin::string);



1;

__END__

=pod

=head1 NAME



=head1 DESCRIPTION

Perl data type class for the XML Schema defined simpleType
OpportunityAttributeType from the namespace https://adwords.google.com/api/adwords/o/v201109.

Represents the type of {@link com.google.ads.api.services.common.optimization.attributes.Attribute}. <p><b>{@link OpportunityIdeaType} KEYWORD supports the following {@link OpportunityAttributeType}s:</b><br/> <ul><li>{@link #ADGROUP_ID}</li> <li>{@link #AVERAGE_MONTHLY_SEARCHES}</li> <li>{@link #CAMPAIGN_ID}</li> <li>{@link #CUSTOMER_ID}</li> <li>{@link #IDEA_TYPE}</li> <li>{@link #KEYWORD}</li> </ul> <p><b>{@link OpportunityIdeaType} BID supports the following {@link OpportunityAttributeType}s:</b><br/> <ul><li>{@link #ADGROUP_ID}</li> <li>{@link #BID_LANDSCAPE}</li> <li>{@link #CAMPAIGN_ID}</li> <li>{@link #CLICKS_CHANGE}</li> <li>{@link #COST_CHANGE}</li> <li>{@link #CURRENT_BID}</li> <li>{@link #CUSTOMER_ID}</li> <li>{@link #IDEA_TYPE}</li> <li>{@link #IMPRESSIONS_CHANGE}</li> <li>{@link #KEYWORD}</li> <li>{@link #NEW_BID}</li> </ul> <p><b>{@link OpportunityIdeaType} BUDGET supports the following {@link OpportunityAttributeType}s:</b><br/> <ul><li>{@link #ADGROUP_ID}</li> <li>{@link #CAMPAIGN_ID}</li> <li>{@link #CLICKS_CHANGE}</li> <li>{@link #COST_CHANGE}</li> <li>{@link #CURRENT_BUDGET}</li> <li>{@link #CUSTOMER_ID}</li> <li>{@link #IDEA_TYPE}</li> <li>{@link #IMPRESSIONS_CHANGE}</li> <li>{@link #NEW_BUDGET}</li> </ul> 



This clase is derived from 
   SOAP::WSDL::XSD::Typelib::Builtin::string
. SOAP::WSDL's schema implementation does not validate data, so you can use it exactly
like it's base type.

# Description of restrictions not implemented yet.


=head1 METHODS

=head2 new

Constructor.

=head2 get_value / set_value

Getter and setter for the simpleType's value.

=head1 OVERLOADING

Depending on the simple type's base type, the following operations are overloaded

 Stringification
 Numerification
 Boolification

Check L<SOAP::WSDL::XSD::Typelib::Builtin> for more information.

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

