package Google::Ads::AdWords::v201109_1::ManualCPM;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'https://adwords.google.com/api/adwords/cm/v201109_1' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}


use base qw(Google::Ads::AdWords::v201109_1::BiddingStrategy);
# Variety: sequence
use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %BiddingStrategy__Type_of :ATTR(:get<BiddingStrategy__Type>);

__PACKAGE__->_factory(
    [ qw(        BiddingStrategy__Type

    ) ],
    {
        'BiddingStrategy__Type' => \%BiddingStrategy__Type_of,
    },
    {
        'BiddingStrategy__Type' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'BiddingStrategy__Type' => 'BiddingStrategy.Type',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

Google::Ads::AdWords::v201109_1::ManualCPM

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
ManualCPM from the namespace https://adwords.google.com/api/adwords/cm/v201109_1.

Manual impression based bidding where user pays per thousand impressions. 




=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over



=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # Google::Ads::AdWords::v201109_1::ManualCPM
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

