package Google::Ads::AdWords::v201109_1::NegativeCampaignCriterion;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'https://adwords.google.com/api/adwords/cm/v201109_1' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}


use base qw(Google::Ads::AdWords::v201109_1::CampaignCriterion);
# Variety: sequence
use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %campaignId_of :ATTR(:get<campaignId>);
my %isNegative_of :ATTR(:get<isNegative>);
my %criterion_of :ATTR(:get<criterion>);
my %CampaignCriterion__Type_of :ATTR(:get<CampaignCriterion__Type>);

__PACKAGE__->_factory(
    [ qw(        campaignId
        isNegative
        criterion
        CampaignCriterion__Type

    ) ],
    {
        'campaignId' => \%campaignId_of,
        'isNegative' => \%isNegative_of,
        'criterion' => \%criterion_of,
        'CampaignCriterion__Type' => \%CampaignCriterion__Type_of,
    },
    {
        'campaignId' => 'SOAP::WSDL::XSD::Typelib::Builtin::long',
        'isNegative' => 'SOAP::WSDL::XSD::Typelib::Builtin::boolean',
        'criterion' => 'Google::Ads::AdWords::v201109_1::Criterion',
        'CampaignCriterion__Type' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'campaignId' => 'campaignId',
        'isNegative' => 'isNegative',
        'criterion' => 'criterion',
        'CampaignCriterion__Type' => 'CampaignCriterion.Type',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

Google::Ads::AdWords::v201109_1::NegativeCampaignCriterion

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
NegativeCampaignCriterion from the namespace https://adwords.google.com/api/adwords/cm/v201109_1.

A negative campaign criterion. 




=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over



=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # Google::Ads::AdWords::v201109_1::NegativeCampaignCriterion
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

