#!/usr/bin/env perl
# ex:ts=4

use strict;
use warnings;

my $cmd = shift || '';
if ($cmd eq 'config') {print qq{graph_title Cyclone3 processes
graph_args --base 1000 -l 0
graph_category cyclone3
graph_order cron pub
graph_vlabel processes
graph_total total
graph_scale no
cron.label cron engine
cron.draw LINE3
pub.label pub engine
pub.draw LINE2
};
	exit 0;
}


my $tom3_value=`ps ax | grep "/core\.tom" | grep -vc "grep"`;chomp($tom3_value);
print "pub.value " . $tom3_value . "\n";

#$tom3_value=`ps ax | grep "\.core/webclick" | grep -vc "grep"`;chomp($tom3_value);
#print "webclick.value " . $tom3_value . "\n";

#$tom3_value=`ps ax | grep "\.core/a542_file_download" | grep -vc "grep"`;chomp($tom3_value);
#print "download.value " . $tom3_value . "\n";

$tom3_value=`ps ax | grep "perl" | grep "cron" | grep -vc "grep"`;chomp($tom3_value);
print "cron.value " . $tom3_value . "\n";
