#!/bin/sh
MD5_USER=`/sbin/md5 -qs "${HTTP_HOST}-${USER}"`
MD5_PASS=`/sbin/md5 -qs "${PASS}"`
MD5_FILE="/www/TOM/_temp/auth-${MD5_USER}-${MD5_PASS}"

if [ -f ${MD5_FILE} ] ; then
	#echo "ok ${HTTP_HOST}-${USER}" >> /www/TOM/_logs/auth.log
	echo 1
else
	/www/TOM/.bin/tom3-auth.full
fi