#!/usr/bin/perl
use Term::ANSIColor;
use Time::HiRes;
BEGIN {
	if (!$ENV{'CYCLONE3PATH'}){$ENV{'CYCLONE3PATH'}="/www/TOM" if -d "/www/TOM";$ENV{'CYCLONE3PATH'}="/Cyclone3" if -d "/Cyclone3";}
	require $ENV{'CYCLONE3PATH'}."/.bin/tom3-init";
}
use Term::InKey;
%form=
(
 '--host'	=>	"restart host (eg. www_localhost_com)",
# '-s'		=>	"show all",
);
if (($FORM{h})||($FORM{help})){&help();}


#open(*STDERR,">/dev/null");

use Proc::ProcessTable;
use DateTime;

while(1)
{
	
	
	# cmdline
	# pctcpu
	# rss
	
	my %hosts;
	
	my $t = new Proc::ProcessTable;
	foreach my $p (@{$t->table})
	{
#		next unless $p->{'cmndline'}=~/(\.core\/tom3|perl.*core\.tom)/;
#		print $p->{'cmndline'}."\n";
		next unless $p->{'cmndline'}=~/^.*\/perl $TOM::P\/[^ ]*\/(.*?)$/;
		my $engine=$1;
		
		my $host;
		$p->{'cmndline'}=~s| pwd=.*$||;
		$p->{'cmndline'}=~/$TOM::P\/(.*)\/(.*?)$/;
		my $pwd=$1;
#			$pwd=~s|^.*?/TOM/||;
			$pwd=~s| $||g;
		
		foreach (split('/',$pwd))
		{
			$_=~s/^!// && do
			{
				if ($host){$host=$_.".".$host;next}
				$host=$_;next;
			};
			$host.="/".$_;
		}
		$host=~s|^www\.||;
		$host=~s|/core\.tom$||;
		
#		foreach (keys %{$p})
#		{
#			print $_ . " = ". $p->{$_} . "\n";
#		}
#		exit;
		push @{$hosts{$host}},{
			'engine'=>$engine,
			'size'=>$p->{'size'},
			'rss'=>$p->{'rss'},
			'pctcpu'=>$p->{'pctcpu'},
			'state'=>$p->{'state'},
			'start'=>$p->{'start'},
			'time'=>$p->{'time'},
			'pid'=>$p->{'pid'}
		};
		
	}
	
#	exit;
	
		my $l;
		foreach my $host(sort keys %hosts)
		{
			$l=length($host) if length($host)>$l;
		}
		
		my $print_out;
		$print_out.=color 'reset bold cyan';
		$print_out.="[DOMAIN(start)".(" " x ($l-13))."][ENGINE   ][STAT ][P ][  CPU][  RSS][START][TIMEm][  PID][IDLEs][  rqs][rq/m][rqcode  ][uri               ]\n";
		$print_out.=color 'reset cyan';
		
		my $processes;
		my $cpu;
		my $rss;
		foreach my $host(sort keys %hosts)
		{
			for (0..@{$hosts{$host}}-1)
			{
				$processes++;
				my $setcolor;
				$hosts{$host}[$_]{'state'}="proc" if $hosts{$host}[$_]{'state'} eq "onprocessor";
				if ($hosts{$host}[$_]{'state'} eq "run"){$setcolor = 'reset bold cyan';}
				if ($hosts{$host}[$_]{'state'} eq "proc"){$setcolor = 'reset bold cyan';}
				else {$setcolor = 'reset cyan';}
				$print_out.=color $setcolor;
				
				# host
				if (!$_){$print_out.="[".sprintf("%-".$l."s",$host)."]";}else {$print_out.=(" " x ($l+2));}
				
				# engine
				$hosts{$host}[$_]{'engine'}=substr($hosts{$host}[$_]{'engine'},0,9);
				$print_out.= "[".sprintf("%-9s",$hosts{$host}[$_]{'engine'})."]";
				
				# STAT
				$print_out.= "[";
				if ($hosts{$host}[$_]{'state'} eq "run"){$print_out.= color 'bold yellow'}
				$print_out.= sprintf("%5s",$hosts{$host}[$_]{'state'});
				$print_out.= color $setcolor;$print_out.= "]";
				
				# P
				$print_out.= "[".sprintf("%2s",$_+1)."]";
				
				# CPU
				$print_out.= "[";
				if ($hosts{$host}[$_]{'pctcpu'} > 1){$print_out.= color 'bold cyan'}
				if ($hosts{$host}[$_]{'pctcpu'} > 10){$print_out.= color 'yellow'}
				if ($hosts{$host}[$_]{'pctcpu'} > 30){$print_out.= color 'bold red'}
				$print_out.= sprintf('%5s',sprintf('%-2.1f',$hosts{$host}[$_]{'pctcpu'}));$print_out.= color $setcolor;$print_out.= "]";
				$cpu+=$hosts{$host}[$_]{'pctcpu'};
				
				# MEM
				$hosts{$host}[$_]{'rss'}=int($hosts{$host}[$_]{'rss'}/1024/1024);
				$print_out.= "[";
				if ($hosts{$host}[$_]{'rss'} > 100){$print_out.= color 'yellow'}
				if ($hosts{$host}[$_]{'rss'} > 200){$print_out.= color 'bold red'}
				$print_out.= sprintf("%4d",$hosts{$host}[$_]{'rss'});$print_out.= color $setcolor;$print_out.= "M]";
				$rss+=$hosts{$host}[$_]{'rss'};
				
				my $dt = DateTime->from_epoch( epoch => $hosts{$host}[$_]{'start'},'time_zone'=>'local');
				$print_out.= "[".sprintf('%02d',$dt->hour).":".sprintf('%02d',$dt->min)."]";
				
				$print_out.= "[";
				if ((time()-$hosts{$host}[$_]{'start'}) > $TOM::max_time*0.5){$print_out.= color 'yellow'};
				if ((time()-$hosts{$host}[$_]{'start'}) > $TOM::max_time*0.8){$print_out.= color 'bold red'};
				$print_out.= sprintf('%5s',int((time()-$hosts{$host}[$_]{'start'})/60)+1);
				$print_out.= color $setcolor;
				$print_out.= "]";
				
				$print_out.= "[".sprintf('%5s',$hosts{$host}[$_]{'pid'})."]";
				
				if ($TOM::CACHE_memcached)
				{
					# additional data
					
					if (my $vals=$Ext::CacheMemcache::cache->get('namespace'=>'c3process','key' => $TOM::hostname.':'.$hosts{$host}[$_]{'pid'}))
					{
						use Data::Dumper;
#						print Dumper($vals);
						
						$print_out.= "[";
						my $idle=(time() - $vals->{'time'});
#						if ($idle > 5){print color 'bold cyan'}
						if ($idle > 60){$print_out.= color 'yellow'}
#						if ($idle > 60){print color 'bold red'}
						if ($idle > 1)
						{
							$print_out.=sprintf('%5s',$idle);
						}
						else
						{
							$print_out.= "     ";
						}
						$print_out.= color $setcolor;$print_out.= "]";
						
						$print_out.= "[".sprintf('%5s',$vals->{'count'})."]";
						
						my $living=(time()-$hosts{$host}[$_]{'start'})/60;
						my $rqs=int($vals->{'count'}/($living||1));
						
						$print_out.= "[";
#						if ($rqs < 1){print color 'bold red'}
						if ($rqs < 10){$print_out.= color 'yellow'}
						elsif ($rqs < 60){}
						else {$print_out.= color 'bold cyan'}
#						if ($rqs > 60){print color 'bold red'}
#						if ($rqs > 60){print color 'bold red'}
						$print_out.=sprintf('%4s',$rqs);
						$print_out.= color $setcolor;$print_out.= "]";
						
						$print_out.= "[";
						if ($vals->{'request_code'}){$print_out.= color 'bold cyan'}
						$print_out.=sprintf('%8s',$vals->{'request_code'});
						$print_out.= color $setcolor;$print_out.= "]";
						
						$print_out.= "[";
						if ($vals->{'request_code'})
						{
							if ($idle >= 5)
							{
								$print_out.= color 'red';
							}
							elsif ($idle >= 2)
							{
								$print_out.= color 'bold yellow';
							}
						}
						$print_out.=sprintf('%.70s',$vals->{'http_host'}.$vals->{'request_uri'});
						$print_out.= "]";
						
					}
				}
				
				$print_out.= "\n";
				
			}
			
			
		}
		
		$print_out.= color 'reset cyan';
		$print_out.= "[TOTAL".(" " x ($l-5))."]                  [". sprintf('%2d',$processes)."][". sprintf('%5s',sprintf('%-2.2f',$cpu)) ."][" .sprintf('%4s',$rss). "M]\n";
		$print_out.= color 'reset cyan';
		
		&Clear();
		print $print_out;
		#print color 'reset bold cyan';print "*";print "\n";
		Time::HiRes::sleep(0.3) unless $FORM{'r'};
#		exit;
	
}




&exit();
