#!/usr/bin/perl
use Term::ANSIColor;
BEGIN {require "/www/TOM/.bin/tom3-init";}

use TOM::Database::connect;
use TOM::Database::SQL;

%form=
(
 '-v'		=>	"verbosity",
 '-vv, --v'	=>	"verbosity 2, --v=2",
 '--db_h'	=>	"use type of database (default main)",
 '--domain'	=>	"use name of domain",
 '--name'	=>	"name of extension or application",
);
if (($FORM{'h'})||($FORM{'help'})||(!$FORM{'name'})){&help();}

if ($FORM{'v'})
{
	$main::debug=1;
}

$FORM{'db_h'}='main' unless $FORM{'db_h'};

#################################################################################################

if ($FORM{'domain'})
{
	require $tom::P."/local.conf";
#	main::_log("name=$TOM::DB{'main'}{'name'} $@");
}
else
{
#	$TOM::DB{'main'}{'name'}="TOM";
}

print color 'reset bold yellow';

foreach my $name (split(',',$FORM{'name'}))
{
	main::_log_stdout "installing '$name' to '$TOM::DB{$FORM{'db_h'}}{'name'}'";
	TOM::Database::SQL::file::install(
		$name,
		'db_h'=>$FORM{'db_h'},
		'db_name'=>$TOM::DB{$FORM{'db_h'}}{'name'},
		'-compare' => 1
	);
	main::_log_stdout "successfully installed";
}


&exit();
