#!/usr/bin/perl
use Term::ANSIColor;
use Mysql;
BEGIN {require "/www/TOM/.bin/tom3-init";};
%form=
(
	'--domain'	=>	"show team for domain (eg. localhost.com)",
#	'-a'		=>	"show config all domains",
);

$CRON::P="/www/TOM";
$cron::P=$CRON::P;
	
if ($FORM{domain})
{
	require $p."/local.conf";
	$cron::P=$main::p;
	#print "$FORM{-category}\n";
	
	
	#print "default language"
	
	foreach (sort keys %TOM::contact)
	{
		next if (not $_=~/^[A-Z]+$/ || $_ eq "manager");
		
		print "[ ".sprintf("%-10s",$_)." ] [ ";
		
		print "[ ".sprintf("%-55s",$TOM::contact{$_})." ]\n";
		
		#print "$_:$TOM::contact{$_}\n";
	}
	
}








&exit();
