#!/usr/bin/perl
use strict;
use Term::ANSIColor;
use open ':utf8', ':std';
#use encoding 'utf8'; - uz si nepamatam preco je toto zakomentovane
use utf8;

BEGIN
{
	$TOM::engine="bin";
	require "/www/TOM/.core/.libs/TOM.pm";
	$TOM::engine_ready=1;
	$TOM::core_uname_n=$TOM::hostname;
	$CRON::core_uname_n=$TOM::hostname;
	
	print color 'bold blue';
	print "[Cyclone3 BIN Control]\n";
	print color 'reset blue';
	print "initializing...";
	chomp ($main::p=`pwd`);
	print " p:".$main::p;
	$main::P=$TOM::P;
	$TOM::P=$main::P;
	print " P:".$main::P."\n";
	unshift @INC,$main::P."/.core/.libs";
}


use TOM::lock;


print color 'bold green';
my $filename=$0;
$filename=~s|.*/||;
print "[$filename]\n";

print color 'reset green';


foreach my $key(@ARGV)
{
	$key=~s/--// && do
	{
		my @ref=split('=',$key,2);
		$ref[1]=1 unless exists $ref[1];
		$main::FORM{$ref[0]}=$ref[1];
		next;
	};
	$key=~s/-// && do
	{
		foreach (split('',$key)){$main::FORM{$_}++;}
	};
}

$main::time_current=time;
(
	$main::Tsec,
	$main::Tmin,
	$main::Thour,
	$main::Tmday,
	$main::Tmom,
	$main::Tyear,
	$main::Twday,
	$main::Tyday,
	$main::Tisdst) = localtime($main::time_current);
   # doladenie casu
   $main::Tyear+=1900;$main::Tmom++;
   # formatujem cas
(
	$main::Fsec,
	$main::Fmin,
	$main::Fhour,
	$main::Fmday,
	$main::Fmom,
	$main::Fyear,
	$main::Fwday,
	$main::Fyday,
	$main::Fisdst
	) = (
	sprintf ('%02d', $main::Tsec),
	sprintf ('%02d', $main::Tmin),
	sprintf ('%02d', $main::Thour),
	sprintf ('%02d', $main::Tmday),
	sprintf ('%02d', $main::Tmom),
	$main::Tyear,
	$main::Twday,
	$main::Tyday,
	$main::Tisdst
	);
	$main::Fyear_sub=$main::Fyear;
	$main::Fyear_sub=~s/^..//;


if ($main::FORM{domain})
{
	$main::FORM{domain}=~s|^www\.||i;
	$main::h=$main::FORM{domain};$main::h=~s|\.|_|g;$main::h=~s|/|__|g;

	my $path=$main::FORM{domain};$path=~s|^(.[^/]*)(.*)||;
	my $path_dom=$1;my $path_sub=$2;
	$path_dom=~s|(.*\.\|)(.*?\..*?)$|$1|;
	$main::p="!$2";$path_dom=~s|\.$||;

	foreach (reverse split('\.',$path_dom)){$main::p.="/!$_";}
	foreach (split('/',$path_sub)){$main::p.="/$_";}

	$main::p=~s|//|/|g;
	$main::p=$main::P."/".$main::p;
	print "p:".$main::p."\n";
	print "h:".$main::h."\n";
	
	$tom::P=$main::p;
	$TOM::P=$main::P;
	
	unshift @INC,$tom::P."/.libs";
}


my $out=`id`;$ENV{USER}=($out=~/\((.*?)\)/)[0];


sub help
{
	print "[using---------------------------------------------------]\n";
	print "[ -h, --help     this page                               ]\n";
	foreach (sort keys %main::form)
	{
		print "[ ";
		print sprintf("%-15s",$_);
		print sprintf("%-40s",$main::form{$_});
		print "]\n";
	}
	print "[--------------------------------------------------------]\n";
	&exit();
}

sub exit
{
	print color 'reset';
	print "\n";
	exit();
}

1;
