#!/usr/bin/perl
use open ':utf8', ':std';
use encoding 'utf8';
use utf8;
use Term::ANSIColor;

BEGIN
{
	if (!$ENV{'CYCLONE3PATH'}){$ENV{'CYCLONE3PATH'}="/www/TOM" if -d "/www/TOM";$ENV{'CYCLONE3PATH'}="/Cyclone3" if -d "/Cyclone3";}
	require $ENV{'CYCLONE3PATH'}."/.bin/tom3-init";
	$main::debug=1;
}

use Time::HiRes qw( usleep ualarm gettimeofday tv_interval );
use CRON;
use CRON::debug;

package main;

$TOM::engine_ready=1;


%form=
(
 '-v'			=>	"verbosity",
 '--domain'	=>	"cron domain",
 '---global'		=>	"cron global",
 '---category'	=>	"cron category",
 '---name'		=>	"cron name",
);
if ((!$FORM{-name}) || ($FORM{h})||($FORM{help})){&help();}

print color 'reset bold blue';

require $ENV{'CYCLONE3PATH'}."/.core/_config/cron.conf";

	$cron::P=$CRON::P;
	
	$TOM::engine="cron";
	
	$CRON::P=$ENV{'CYCLONE3PATH'};
	$cron::P=$CRON::P;
	
	if ($FORM{'domain'})
	{
#		require $main::p."/local.conf"; # local.conf already loaded
		$cron::P=$main::p;
		$tom::P=$main::p;
		main::_log("main db=$TOM::DB{'main'}{'name'}");
	}
	else
	{
		$TOM::DB{'main'}{'name'}="TOM";
	}
	
	module(%FORM);
	
	&exit();
	