#!/usr/bin/perl
use Term::ANSIColor;
require "/usr/bin/tom3-init";

%form=
(
# '-v'		=>	"verbosity",
# '-vv, --v'	=>	"verbosity 2, --v=2",
 '-e'		=>	"execute all modifications",
# '-s'		=>	"show only all modifications",
# '-a'	=>	"all directories",
# '-t'	=>	"this directory",
# '-r'	=>	"this directory with recursive",
 '-v'	=>	"verbosity",
);
if (($FORM{h})||($FORM{help})){&help();}
if (!$FORM{e}){&help();}

my $time_current=time;

chdir $TOM::P;


# test system dirs
system("mkdir -p _data");
system("mkdir -p _temp");
system("mkdir -p _trash");
system("mkdir -p _downgrade");

print "install.csh\n";
system("cd /www/TOM/.bin/;./install.csh");

=head1
print "replace configs\n";
chdir $TOM::P;
foreach my $file (grep {$_=~/(master|local).conf$/} split ("\n",`find .|grep conf`))
{
	$file=~s|^\./||;
	print "$file\n";
	
	open (HND,"<$file");undef $/;my $file_data=<HND>;close(HND);
	
	my $change;
	
	while ($file_data=~s|\$tom::type_c\{(.*?)\}.*?"([mg0-9])([0-9]+)?"|\$tom::type_c{$1}	=	"<!REPLACE!>"|)
	{
		$change++;
		my $TID=$2.$3;
		
		my $TIDn;
		if ($TID=~/^([mg0-9])([0-9]+)?$/)
		{
			my $pre=$1;
			my $post=$2;
			if (not $pre=~/[lmg]/)
			{
				$post=$pre.$post;
				$pre="l";
			}
			
			$TIDn=$pre."_".sprintf('%04d',$post);
		}
		
		print "\treplace $TID to $TIDn\n";
		
		$file_data=~s|<!REPLACE!>|$TIDn|g;
	}
	
	if ($change)
	{
		print "file changed\n";
		system ("cp $file $file.old");
		open (HND,">$file");print HND $file_data;close(HND);
	}
}
=cut

=head1
print "\n";
print "replace types\n";
chdir $TOM::P;
foreach my $file (grep {$_=~/\/([mg0-9])([0-9]+)\.cml_type$/} split ("\n",`find .|grep cml_type`))
{
	my $TID=($file=~/^.*\/(.*?)\.cml_type$/)[0];
	next if ($TID eq "mpre" || $TID eq "pre");
	
	$file=~s|^\./||;
	print "$file TID=$TID\n";
	
	my $TIDn;
	if ($TID=~/^([mg0-9])([0-9]+)?$/)
	{
		my $pre=$1;
		my $post=$2;
		if (not $pre=~/[lmg]/)
		{
			$post=$pre.$post;
			$pre="l";
		}	
		$TIDn=$pre."_".sprintf('%04d',$post);
	}
	
	my $filen=$file;
	$filen=~s|(.*/).*|$1|;
	$filen.=$TIDn.".pub.type";
	print "\t$filen\n";
	
	system("cp $file $file.old");
	system("cp $file $filen");
	system("rm $file");
}
=cut



#system("tom3-chfiles -a");

#system("/usr/local/apache/bin/apachectl restart");









