#!/usr/bin/perl
use Term::ANSIColor;

BEGIN {require "/www/TOM/.bin/tom3-init";}


%form=
(
	'-v'	=>	"verbosity",
);
if (($FORM{h})||($FORM{help})){&help();}

my $time_current=time;

chdir $TOM::P;

system ('tar --exclude ".core/*" --exclude "*.log" --exclude "*.tar" --exclude "*.gz" --exclude "!www/*" --exclude "!media*" --exclude "_data/*" --exclude "_temp/*" --exclude "*.asf" --exclude "*.jpg" --exclude "_trash/*" -cvvzf _temp/tom3_domain.'.$time_current.'.tar.gz .');

print "chown tar...\n";
system ("chown tom:tom _temp/tom3_domain.".$time_current.".tar.gz");
print "chmod tar...\n";
system ("chmod 600 _temp/tom3_domain.".$time_current.".tar.gz");