#!/usr/bin/perl
use Term::ANSIColor;
use Mysql;
BEGIN {require "/www/TOM/.bin/tom3-init";$main::debug=0;}

use TOM::Database::connect;
use TOM::Database::SQL;

%form=
(
 '-v'		=>	"verbosity",
 '-vv, --v'	=>	"verbosity 2, --v=2",
 '-e'		=>	"execute all modifications",
 '--db_h'	=>	"use type of database",
 '--db_name'	=>	"use name of database",
);
if (($FORM{'h'})||($FORM{'help'})){&help();}

if (!$FORM{'db_h'}){&help();}

#################################################################################################

$TOM::DB{'main'}{'name'}="TOM";
TOM::Database::connect::multi($FORM{'db_h'}) || die "can't connect";

print "connected '$FORM{'db_h'}' database handler\n";

if ($FORM{'db_name'})
{
	my %out=TOM::Database::SQL::compare::compare_database($FORM{'db_name'},'db_h'=>$FORM{'db_h'});
	print "compared database '$FORM{'db_name'}'\n";
	print color 'reset bold yellow';
	foreach my $SQL(@{$out{'ALTER'}})
	{
		print "$SQL\n";
	}
	
	print "Do it? [No/yes]\n";
	my $do=<STDIN>;
	
	if ($do=~/yes/i)
	{
		print color 'reset red';
		foreach my $SQL(@{$out{'ALTER'}})
		{
			print "$SQL\n";
			TOM::Database::SQL::execute($SQL);
		}
	}
	
}


&exit();
