#!/usr/bin/perl
use Term::ANSIColor;
BEGIN {require "/usr/bin/tom3-init";}
use Mysql;
use Utils::datetime;
use Benchmark;
use TOM::Net::URI::URL;
use Utils::vars;
use enc3;
use MIME::Base64;

#print color 'bold green';

%form=
(
 '--host'	=>	"cache domain (eg. localhost.com)",
 '--type'	=>	"type of cron (eg. 5min, 30min, ...)",
 '-v'		=>	"verbose all",
# '--verb'	=>	"verbose number",
# '--del'	=>	"delete number",
# '--edit'	=>	"edit number",
# '-vv, --v'	=>	"verbosity 2, --v=2",
# '-a'		=>	"analyze",
# '-s'		=>	"show only all modifications",
);
if (($FORM{h})||($FORM{help})){&help();}





for (1..100000)
{
	
	
	
	my $hash=Utils::vars::genhash_ABS(int(rand(500)));
	#print "$hash\n";
	
	print "$_\n";
						
						
						# kodovanie
						
						$null=$tom::type_code[int(rand(@tom::type_code))];
						
						
						my $var=enc3::xor($hash,$tom::code_keys{$null}{key});
						
						$var=MIME::Base64::encode_base64($var);
						$var=~s|[\n\r]||;
						$var=~s|==$||;
						$var=TOM::Net::URI::URL::url_encode($var) if $var; # hex encoding
						
						# dekodovanie
						
						$var=TOM::Net::URI::URL::url_decode($var);
						$var.="==";
						$var=MIME::Base64::decode_base64($var);
						$var=enc3::xor($var,$tom::code_keys{$null}{key});
						
						if ($var ne $hash)
						{
							print "zle! $hash + $null \n";
							exit;
						}
						
						
	#print "$var\n";
	
	
}











&exit();
