#!/usr/bin/perl
use Digest::MD5  qw(md5 md5_hex md5_base64);

$pass_md5=md5_hex($ENV{'PASS'});
$user_md5=md5_hex($ENV{'HTTP_HOST'}.'-'.$ENV{'USER'});
$filename="/www/TOM/_temp/auth-".$user_md5."-".$pass_md5;

my $cache=1;

if (-e $filename && $cache)
{
	exit(0);
}
else
{
	my $out;
	chomp ($out=`/www/TOM/.bin/tom3-auth.full`);
	exit($out);
	#exit(0); # password okay
	#exit(1); # password bad
}