#!/usr/bin/perl
use Term::ANSIColor;
require "/usr/bin/tom3-init";

#print color 'bold green';
my %hash;





if (opendir (DIR,$P))
{
 my @files=readdir DIR;
 foreach my $file(@files)
 {
  if (($file ne ".")&&($file ne ".."))
  {
   my $dir;
   if (-d $P."/".$file){$dir="-D "}
   #print "[$pcount] $file\t\r";

   if ($dir)
   {
    if (opendir (DIR1,$P."/".$file)){foreach (readdir DIR1){if (($_ ne ".")&&($_ ne "..")){push @files,$file."/".$_;}}}
   }

   if ($file=~/mdl$/)
   {
    my $file_data;
    open (HND,"<$P/$file");
    while (my $file_line=<HND>){$file_data.=$file_line;}
    if ($file_data=~/$ARGV[0]/s)
    {
     print $file."\n";
    }

   }

  }
 }
 closedir DIR;
}
print "\n";
#print color 'reset blue';









&exit();
