#!/usr/bin/perl
use Term::ANSIColor;
use Mysql;
BEGIN {require "/www/TOM/.bin/tom3-init";$main::debug=0;}

use TOM::Database::connect;
use TOM::Database::SQL;

%form=
(
 '-v'		=>	"verbosity",
 '-vv, --v'	=>	"verbosity 2, --v=2",
 '-e'		=>	"execute all modifications",
 '--db_h'	=>	"use type of database (default main)",
 '--domain'	=>	"use name of domain",
);
if (($FORM{'h'})||($FORM{'help'})){&help();}

if ($FORM{'v'})
{
	$main::debug=1;
}

$FORM{'db_h'}='main' unless $FORM{'db_h'};

#################################################################################################

$TOM::DB{'main'}{'name'}="TOM";
TOM::Database::connect::multi($FORM{'db_h'}) || die "can't connect";

print "connected '$FORM{'db_h'}' database handler\n";


if ($FORM{'domain'})
{
	require $tom::P."/local.conf";
	
	my %out=TOM::Database::SQL::compare::compare_database(
		$TOM::DB{$FORM{'db_h'}}{'name'},
		'db_h'=>$FORM{'db_h'}
	);
	print "compared database '$TOM::DB{$FORM{'db_h'}}{'name'}'\n";
	print color 'reset bold yellow';
	foreach my $SQL(@{$out{'ALTER'}})
	{
		print "$SQL\n";
	}
	
	if (@{$out{'ALTER'}})
	{
		print "Do it? [No/yes]\n";
		my $do=<STDIN>;
		if ($do=~/yes/i)
		{
			print color 'reset red';
			foreach my $SQL(@{$out{'ALTER'}})
			{
				print "$SQL\n";
				TOM::Database::SQL::execute($SQL);
			}
		}
	}
	
}
else
{
	# default aplikacie instalovane v TOM
	foreach my $app(@TOM::default_TOM_App)
	{
		TOM::Database::SQL::file::install(
			'a'.$app,
			'db_name'=>'TOM',
			'db_h'=>$FORM{'db_h'},
		);
	}
	
	my %out=TOM::Database::SQL::compare::compare_database(
		'TOM',
		'db_h'=>$FORM{'db_h'}
	);
	print "compared database 'TOM'\n";
	print color 'reset bold yellow';
	foreach my $SQL(@{$out{'ALTER'}})
	{
		print "$SQL\n";
	}
	
	if (@{$out{'ALTER'}})
	{
		print "Do it? [No/yes]\n";
		my $do=<STDIN>;
		if ($do=~/yes/i)
		{
			print color 'reset red';
			foreach my $SQL(@{$out{'ALTER'}})
			{
				print "$SQL\n";
				TOM::Database::SQL::execute($SQL);
			}
		}
	}
	
}


&exit();
