#!/usr/bin/perl
use utf8;

BEGIN
{
	$tom::P=`pwd` unless $ENV{SCRIPT_FILENAME} && do
	{$tom::P=$ENV{SCRIPT_FILENAME};$tom::P=~s|(.*)/.*?/||;$tom::P=$1;};
	$tom::P=~s|(.*)/.*?\n$|\1|;
	$TOM::P="/www/TOM";
	unshift @INC,$TOM::P."/_mdl"; # na zaciatok
	unshift @INC,$TOM::P."/.core/.libs"; # na zaciatok
	sub _log{return};sub _applog{return};
}


use strict; # scrict code
use Inline (Config => DIRECTORY => "$TOM::P/.core/.libs/_Inline");

use FCGI;
require $TOM::P."/.core/_config/TOM.conf";
require $TOM::P."/_config/TOM.conf";

use Mysql;
use Time::Local;
use Time::HiRes qw( usleep ualarm gettimeofday tv_interval );
use MIME::Base64;

use Net::HTTP::cookies;

use TOM;
use TOM::Engine::pub;
use TOM::Database::connect;
use TOM::Data::XML;
use TOM::Text::format;
use TOM::Net::URI::URL;
use TOM::Net::URI::rewrite;
use TOM::Net::HTTP::CGI;

use App::540::_init;
use App::540::file;

use enc3;


# domain configuration
require $tom::P."/local.conf";

######################################################################################

TOM::Database::connect::multi('main');


my $req=FCGI::Request();
while ($req->Accept() >= 0)
{
	my %env;
	my $time_current=time;
	
	my %FORM=TOM::Net::HTTP::CGI::GetQuery($ENV{'QUERY_STRING'} || $ARGV[0]);
	
	main::_log("QUERY_STRING='$ENV{QUERY_STRING}'");
	
	my @file = App::540::file::get( hash => $FORM{hash}, ID => $FORM{hash2} );
	
	main::_log("file='$file[0]{fullpath}' @file");
	
	if (scalar(@file) == 0 || !open FILE,$file[0]{fullpath})
	{
		print "Status: 404 Not Found\n\n";
		next;
	}
	
	my %user = &Net::HTTP::cookies::GetCookies;
	
	my $ip = $ENV{REMOTE_ADDR};
	my $host = gethostbyaddr( pack( 'C4', split( '\.', $ip) ), 2);
	
	main::_log("logging: file:".$file[0]{ID}." user:".$user{_IDhash});
	$main::DB{main}->Query("
		INSERT INTO a540_visits
		(
			IDfile,
			IDuser,
			time_insert,
			IP,
			dns
		)
		VALUES
		(
			'".$file[0]{ID}."',
			'".$user{_IDhash}."',
			'".time()."',
			'$ip',
			'$host'
		)
	");
	
	print "Content-Type: $file[0]{mime}\n";
	my $filename=TOM::Net::URI::rewrite::convert($file[0]{name},'notlower'=>1);
	print "Content-Disposition: attachment; filename = ".$filename."\n\n";
	print while <FILE>;
	close FILE;
	
}

######################################################################################

1;
