#!/usr/bin/perl
use open ':utf8', ':std';
use encoding 'utf8';
use utf8;
use strict; # scrict code

# ÁÉÍÓÚ - USE UTF-8!!!

# BEGIN COMPILATION
BEGIN
{
 # -END-
 $tom::P=`pwd` unless $ENV{SCRIPT_FILENAME} && do
 {$tom::P=$ENV{SCRIPT_FILENAME};$tom::P=~s|(.*)/.*?/||;$tom::P=$1;};
 $tom::P=~s|(.*)/.*?\n$|\1|;
 $tom::SCRIPT_NAME=$0;
 $tom::fastcgi=1 if $tom::SCRIPT_NAME=~/(tom|fcgi|fpl)$/; # zistujem ci som fastcgi script
 die "cannot search TOM directory /var/www/TOM/???" unless $TOM::P=`ls -l $tom::SCRIPT_NAME`;
 $TOM::P=~s|.* (.*)/.*?/(.*)\n|\1|;$TOM::SCRIPT_NAME=$2;
 #push @INC,$TOM::P."/.core/.libs"; # na koniec
 unshift @INC,$TOM::P."/_mdl"; # na zaciatok
 unshift @INC,$TOM::P."/.core/.libs"; # na zaciatok
 sub _log{return};sub _applog{return};
}

# START SCRIPT
use strict; # scrict code
use Inline (Config => DIRECTORY => "$TOM::P/.core/.libs/_Inline");

# PERL MODULES
use FCGI;
require $TOM::P."/.core/_config/TOM.conf";
require $TOM::P."/_config/TOM.conf";
#use Tomahawk::error;

 # SYSTEM MODULES
 use Mysql;
 use Database::connect;
 use Time::Local; # pre opacnu konverziu casu
 use Time::HiRes qw( usleep ualarm gettimeofday tv_interval );
 use Net::HTTP::CGI;
 use TOM::Data::XML;
 use TOM::Text::format;
 use MIME::Base64;
 use TOM::Net::URI::URL;
 use enc3;
 
  
 # CORE CONFIGURE MODULES
 require $tom::P."/local.conf";
 
 foreach (keys %tom::code_keys){push @tom::type_code,$_ unless $tom::code_keys{$_}{notuse};}


######################################################################################
######################################################################################
######################################################################################
######################################################################################
Database::connect::multi('main');

my $req=FCGI::Request();
while ($req->Accept() >= 0)
{
	my %env;  
	my $time_current=time;
	
=head1
	my (
	$Tsec,
	$Tmin,
	$Thour,
	$Tmday,
	$Tmom,
	$Tyear,
	$Twday,
	$Tyday,
	$Tisdst) = localtime($main::time_current);
   # doladenie casu
	$Tyear+=1900;$Tmom++;
   # formatujem cas
	my (
	$Fsec,
	$Fmin,
	$Fhour,
	$Fmday,
	$Fmom,
	$Fyear,
	$Fwday,
	$Fyday,
	$Fisdst
	) = (
	sprintf ('%02d', $Tsec),
	sprintf ('%02d', $Tmin),
	sprintf ('%02d', $Thour),
	sprintf ('%02d', $Tmday),
	sprintf ('%02d', $Tmom),
	$Tyear,
	$Twday,
	$Tyday,
	$Tisdst
	);
=cut
	#print "$ARGV[0]\n";
	my %FORM=GetQuery_h2($ENV{'QUERY_STRING'} || $ARGV[0]);
	#my %FORM=GetQuery_h2($ARGV[0]);
	#print "$FORM{ID}\n";
	$FORM{ID}=1 unless $FORM{ID};
	$FORM{lng}="sk" unless $FORM{lng};
#	subtitle LIKE '$FORM{ID}' OR
#	subtitle LIKE '%;$FORM{ID}' OR
#	subtitle LIKE '$FORM{ID};%' OR
	
	my %hash;
	#$hash{ahoj}="asdf";
	my $db0=$main::DB{main}->Query("
		SELECT a400.*,a400_attrs.phone
		FROM a400
		LEFT JOIN a400_attrs ON
		(
			a400.IDattrs = a400_attrs.IDattrs
		)
		WHERE
		(
			a400.subtitle LIKE '$FORM{ID}' OR
			a400.subtitle LIKE '%;$FORM{ID}' OR
			a400.subtitle LIKE '$FORM{ID};%' OR
			a400.subtitle LIKE '%;$FORM{ID};%'
		)
		AND (a400.lng='$FORM{lng}' OR a400.lng='')
	");
	while (my %db0_line=$db0->fetchhash())
	{
		
#=head1
		while ($db0_line{xrelated}=~s/a500_category" value="([\d\w]+)//)
		{
			if ($1)
			{
				my $db1=$main::DB{main}->Query("
					SELECT *
					FROM a500
					WHERE IDcategory='$1' AND format='t'
					ORDER BY ID ASC
				");
				if (my %db1_line=$db1->fetchhash())
				{
					my $null=($db1_line{ID}=~/^(....)/)[0];
					
					push @{$db0_line{xrelated_cat_image}}, "http://media.shoppingpalace.sk/500/".$null."/".$db1_line{hash}."-t.jpg";
					
					#$db0_line{image}="http://media.shoppingpalace.sk/500/".$null."/".$db1_line{hash}."-t.jpg";
				}
			}
		}
#=cute
#=head1
		while ($db0_line{xrelated}=~s/a500" value="([\d\w]+)//)
		{
			if ($1)
			{
				my $db1=$main::DB{main}->Query("
					SELECT *
					FROM a500
					WHERE ID='$1' AND format='o'
					ORDER BY ID ASC
				");
				if (my %db1_line=$db1->fetchhash())
				{
					my $null=($db1_line{ID}=~/^(....)/)[0];
					
					push @{$db0_line{xrelated_full_image}}, "http://media.shoppingpalace.sk/500/".$null."/".$db1_line{hash}."-t.jpg";
					
					#$db0_line{image}="http://media.shoppingpalace.sk/500/".$null."/".$db1_line{hash}."-t.jpg";
				}
			}
		}
#=cut
		delete $db0_line{xrelated};
		
		$db0_line{full}=TOM::Text::format::xml2plain($db0_line{full});
		$db0_line{full}=~s|&nbsp;| |g;
		
		my $null=$tom::type_code[int(rand(@tom::type_code))];
		my $null=$tom::code_key_root;
		#print "!".$null."!";
		my $var=enc3::xor('type=predajna-galeria&ID='.$db0_line{ID},$tom::code_keys{$null}{key});
		$var=MIME::Base64::encode_base64($var);
		$var=~s|[\n\r]||;
		$var=~s|==$||;
		$var=TOM::Net::URI::URL::url_encode($var) if $var; # hex encoding
		$db0_line{'gallery_link'}=$tom::Hm_www."/?__".$var."-".$null."-v3";
		
		push @{$hash{'xml'}{'article'}}, {%db0_line};
		
		
	}
	#$hash{'xml'}{'generated'}=time;
	#$hash{'xml'}{'query'}=$ENV{'QUERY_STRING'}."/".$ARGV[0];
	#$hash{'xml'}{'testamp'}="toto je nejaky &amp; text";
	
	my $out=TOM::Data::XML::serialize_enh(data=>\%hash,strict=>1);
	
	
=head1
	$main::DB{stats}->Query("
		INSERT INTO TOM.a110_webclick_log
		(
			domain,
			domain_sub,
			TID,
			time_insert,
			x,
			y,
			logged,
			IDuser
		)
		VALUES
		(
			'$tom::Hm',
			'$tom::H',
			'$FORM{TID}',
			'$time_current',
			'$FORM{x}',
			'$FORM{y}',
			'$FORM{l}',
			'$FORM{u}'
		)
	");
=cut
	
	#print "Location: http://toaster.markiza.sk/grf/tvn/t.gif\n\n";
	
	print "Content-type: text/xml\n\n";
	print $out."\n";
	
	#print "$tom::Hm, $tom::H, $FORM{TID}, $FORM{x}, $FORM{y}\n";
	
	
}
######################################################################################
######################################################################################
######################################################################################
######################################################################################
