#!/usr/bin/perl
use utf8;
# ÁÉÍÓÚ - USE UTF-8!!!

# BEGIN COMPILATION
BEGIN
{
 # -END-
 $tom::P=`pwd` unless $ENV{SCRIPT_FILENAME} && do
 {$tom::P=$ENV{SCRIPT_FILENAME};$tom::P=~s|(.*)/.*?/||;$tom::P=$1;};
 $tom::P=~s|(.*)/.*?\n$|\1|;
 $tom::SCRIPT_NAME=$0;
 #$tom::fastcgi=1 if $tom::SCRIPT_NAME=~/(tom|fcgi|fpl)$/; # zistujem ci som fastcgi script
 die "cannot search TOM directory /var/www/TOM/???" unless $TOM::P=`ls -l $tom::SCRIPT_NAME`;
 #$TOM::P=~s|.* (.*)/.*?/(.*)\n|\1|;$TOM::SCRIPT_NAME=$2;
 $TOM::P="/www/TOM";
 #push @INC,$TOM::P."/.core/.libs"; # na koniec
 unshift @INC,$TOM::P."/_mdl"; # na zaciatok
 unshift @INC,$TOM::P."/.core/.libs"; # na zaciatok
 sub _log{return};sub _applog{return};
}

# START SCRIPT
use strict; # scrict code
use Inline (Config => DIRECTORY => "$TOM::P/.core/.libs/_Inline");

# PERL MODULES
use FCGI;
require $TOM::P."/.core/_config.sg/TOM.conf";
require $TOM::P."/_config/TOM.conf";
#use Tomahawk::error;

 # SYSTEM MODULES
 use Mysql;
 use MIME::Base64;
 use Time::Local; # pre opacnu konverziu casu
 use Time::HiRes qw( usleep ualarm gettimeofday tv_interval );
 use Database::connect;
 use Net::HTTP::CGI;
 use TOM::Data::XML;
 use TOM::Text::format;
 use TOM::Net::URI::URL;
 use enc3;
 
  
 # CORE CONFIGURE MODULES
 #require $tom::P."/local.conf";
 
 foreach (keys %tom::code_keys){push @tom::type_code,$_ unless $tom::code_keys{$_}{notuse};}


######################################################################################
######################################################################################
######################################################################################
######################################################################################
Database::connect::multi('main');

my $req=FCGI::Request();
while ($req->Accept() >= 0)
{
	my %env;  
	my $time_current=time;
	
	my %FORM=GetQuery_h2($ENV{'QUERY_STRING'} || $ARGV[0]);
	
	open (HND,"<index.html");undef $/;
	my $text=<HND>;
	TOM::Text::format::decode_URLS($text);
	
}
######################################################################################
######################################################################################
######################################################################################
######################################################################################
