#!/usr/bin/perl


BEGIN
{
	$TOM::engine='wc';
	$main::debug=1;# if $ENV{'TERM'};
	require "/www/TOM/.core/.libs/TOM.pm";
}

use open ':utf8', ':std';
use encoding 'utf8';
use utf8; # encode = fromutf8, decode=toutf8
use strict; # scrict code
use CGI::Fast qw(:standard);

use enc3;
use iconv;

my $t=track TOM::Debug("TOM engine '$TOM::engine' initializing...");

use TOM::Database::connect;
use TOM::Database::SQL;
use TOM::Net::HTTP::CGI;

$t->close();

my $t_domain=track TOM::Debug("Domain initialization");
eval
{
	# Load domain configuration
	require TOM::Domain;	
	$TOM::engine_ready=1;
};

if ($@)
{
	my @ERR=("Error occured during domain initialization");
	push @ERR,$@;
	main::_log("request in domain initialization error",1);
	TOM::Error::engine(@ERR);
	exit(0);
}

$t_domain->close;

our $CGI;
while ($main::CGI=new CGI::Fast())
{
	
	my %FORM=TOM::Net::HTTP::CGI::get_QUERY_STRING($ENV{'QUERY_STRING'});
	
	my $sql=qq{
		INSERT DELAYED INTO TOM.a110_webclick_log
		(
			domain,
			domain_sub,
			TID,
			datetime_insert,
			x,
			y,
			logged,
			IDuser
		)
		VALUES
		(
			'$tom::Hm',
			'$tom::H',
			'$FORM{TID}',
			NOW(),
			'$FORM{x}',
			'$FORM{y}',
			'$FORM{l}',
			'$FORM{u}'
		)
	};
	
	TOM::Database::SQL::execute($sql,'db_h'=>'stats');
	
	print "Location: http://media.webcom.sk/grf/t.gif\n\n";
	
}

