#!/usr/bin/env perl
# ex:ts=4
BEGIN {
	if (!$ENV{'CYCLONE3PATH'})
	{
		$ENV{'CYCLONE3PATH'}="/www/TOM" if -d "/www/TOM";
		$ENV{'CYCLONE3PATH'}="/Cyclone3" if -d "/Cyclone3";
		$ENV{'CYCLONE3PATH'}="/srv/Cyclone3" if -d "/srv/Cyclone3";
	}
	require $ENV{'CYCLONE3PATH'}."/.bin/c3-init";
}

use strict;
use open ':utf8', ':std';
use if $] < 5.018, 'encoding','utf8';
use utf8;
use DateTime;
use Ext::Redis::_init;
use Data::Dumper;

my $cmd = shift || '';
if ($cmd eq 'config') {print qq{graph_title Cyclone3 500 requests ($TOM::domain)
graph_args --base 1000
graph_category cyclone3
graph_vlabel requests / minute
graph_order req
graph_scale no
req.label Requests
req.min 0
};
	exit 0;
}

#my $datetime_now=DateTime->now('time_zone' => 'local');

$Ext::Elastic = $Ext::Elastic_rlog_hd{$main::arg{'hd'}}
	|| $Ext::Elastic_rlog
	|| $Ext::Elastic;
require Ext::Elastic::_init;
#main::_log_stdout("ElasticSearch @".join(',@',@{$Ext::Elastic->{'nodes'}}));
$Ext::Elastic->{'request_timeout'} = 300;
Ext::Elastic::_connect();
our $Elastic=$Ext::Elastic::service;

my $td = DateTime->now('time_zone'  => 'GMT');
my $limit=0;
my $indice='logstash-'.$td->strftime('%Y-%m-%d');

my @filter;
my %query_string;

push @filter,{"range" => {'@timestamp' => {'gte' => 'now-5m'}}};

push @filter,{"terms" => {"hd" => [$TOM::domain]}};
push @filter,{"terms" => {"t" => ['cyclone3.pub.track']}};

push @filter,{"range" => {'data.response_status_i' => {'gte' => 500}}};
#push @filter,{"terms" => {"data.response_status_i" => [500]}};

my $search_config={
	'index' => $indice,
	'type' => 'fluentd',
	'size' => $limit,
	'timeout' => '20s',
	'body'  => {
		'timeout' => '20s',
		'query' => {
			'filtered' => {
				'filter' => {
					'bool' => {
						'must' => [@filter]
					}
				},
				%query_string
			}
		}
	}
};

my $results = $Elastic->search($search_config);

print "req.value ".(int($results->{'hits'}->{'total'}/5*10)/10)."\n";

