#!/usr/bin/env perl
# ex:ts=4
BEGIN {
	if (!$ENV{'CYCLONE3PATH'})
	{
		$ENV{'CYCLONE3PATH'}="/www/TOM" if -d "/www/TOM";
		$ENV{'CYCLONE3PATH'}="/Cyclone3" if -d "/Cyclone3";
		$ENV{'CYCLONE3PATH'}="/srv/Cyclone3" if -d "/srv/Cyclone3";
	}
	require $ENV{'CYCLONE3PATH'}."/.bin/c3-init";
}

use strict;
use open ':utf8', ':std';
use if $] < 5.018, 'encoding','utf8';
use utf8;
use DateTime;
use Ext::Redis::_init;
use Data::Dumper;

my $cmd = shift || '';
if ($cmd eq 'config') {print qq{graph_title Cyclone3 SQL queries (all hosts)
graph_category cyclone3
graph_vlabel queries/second
graph_scale no
graph_args --base 1000 -l 0
};
#	exit 0;
}

my $debug;
	$debug=1 if $cmd eq "debug";

my $datetime_now=DateTime->now('time_zone' => 'local');

my $i;
my %db_h;

for (1..2)
{
	$datetime_now->add('minutes' => -1);
	
	my $date_str=
		sprintf('%04d',$datetime_now->year()).'-'.sprintf('%02d',$datetime_now->month()).'-'.sprintf('%02d',$datetime_now->day())
		.' '
		.sprintf('%02d',$datetime_now->hour()).":".sprintf('%02d',$datetime_now->minute());
	
	my %data=@{$Redis->hgetall('C3|counters|sql|'.$date_str)};
	print Dumper(\%data) if $cmd eq "debug";
	
	foreach (grep {$_=~/\|(r_exec|w_exec|cache_hit)$/} keys %data)
	{
		$_=~s/\|(.*?)$//;
		my $type=$1;
		my $h=$_;
			$h=~s|:|_|;
		$db_h{$h}{$type}+=$data{$_.'|'.$type};
	}
}

print Dumper(\%db_h) if $cmd eq "debug";

if ($cmd eq 'config') {
	print "graph_order ".join(" ",sort keys %db_h)."\n";
	foreach my $db (sort keys %db_h)
	{
		print qq{$db\_r.label $db [r]
$db\_r.min 0
$db\_r.draw LINE
$db\_w.label $db [w]
$db\_w.min 0
$db\_w.draw LINE
$db\_c.label $db [c]
$db\_c.min 0
$db\_c.draw LINE
};
	}
	exit 0;
}

foreach my $db (sort keys %db_h)
{
	print "$db\_r.value ".(int($db_h{$db}{'r_exec'}/2/60*10)/10)."\n";
	print "$db\_w.value ".(int($db_h{$db}{'w_exec'}/2/60*10)/10)."\n";
	print "$db\_c.value ".(int($db_h{$db}{'cache_hit'}/2/60*10)/10)."\n";
#		if $db_h{$db}{'exec'};
#	print "$db.value ".int($db_h{$db}{'durr'}/$db_h{$db}{'exec'})."\n"
#		if $db_h{$db}{'exec'};
}

