#!/usr/bin/env perl
# ex:ts=4
BEGIN {
	if (!$ENV{'CYCLONE3PATH'})
	{
		$ENV{'CYCLONE3PATH'}="/www/TOM" if -d "/www/TOM";
		$ENV{'CYCLONE3PATH'}="/Cyclone3" if -d "/Cyclone3";
		$ENV{'CYCLONE3PATH'}="/srv/Cyclone3" if -d "/srv/Cyclone3";
	}
	require $ENV{'CYCLONE3PATH'}."/.bin/c3-init";
}

use strict;
use open ':utf8', ':std';
use if $] < 5.018, 'encoding','utf8';
use utf8;
use DateTime;
use Ext::Redis::_init;
use Data::Dumper;

my $cmd = shift || '';
if ($cmd eq 'config') {print qq{graph_title Cyclone3 availability
graph_args --base 1000 --lower-limit 0
graph_category cyclone3
graph_vlabel milliseconds
graph_order proc req
proc.label CPU
proc.draw AREA
proc.min 0
proc.colour 0022ff
req.label IOWAIT
req.draw STACK
req.min 0
req.colour ffcc00
total.colour 000000
total.label total
total.draw LINE0
total.warning 300
total.critical 700
};
	exit 0;
}

my $debug;
	$debug=1 if $cmd eq "debug";

my $datetime_now=DateTime->now('time_zone' => 'local');
	$datetime_now->add('minutes' => 1);

my $i;
my $value_req;
my $value_proc;

for (1..5)
{
	$datetime_now->add('minutes' => -1);
	
	my $date_str=
		sprintf('%04d',$datetime_now->year()).'-'.sprintf('%02d',$datetime_now->month()).'-'.sprintf('%02d',$datetime_now->day())
		.' '
		.sprintf('%02d',$datetime_now->hour()).":".sprintf('%02d',$datetime_now->minute());
	
	my %data=@{$Redis->hgetall('C3|counters|pub_bench|'.$TOM::hostname.'|'.$date_str)};
	$i+=$data{'cnt'};
	$value_req+=$data{'eval_req'};
	$value_proc+=$data{'eval_proc'};
}

$i||=1;
print "req.value " . int(($value_req - $value_proc)/$i) . "\n";
print "proc.value " . int($value_proc/$i) . "\n";
print "total.value " . int(($value_req)/$i) . "\n";


