#!/usr/bin/env perl
# ex:ts=4
BEGIN {
	if (!$ENV{'CYCLONE3PATH'})
	{
		$ENV{'CYCLONE3PATH'}="/www/TOM" if -d "/www/TOM";
		$ENV{'CYCLONE3PATH'}="/Cyclone3" if -d "/Cyclone3";
		$ENV{'CYCLONE3PATH'}="/srv/Cyclone3" if -d "/srv/Cyclone3";
	}
	require $ENV{'CYCLONE3PATH'}."/.bin/c3-init";
}

use strict;
use open ':utf8', ':std';
use encoding 'utf8';
use utf8;
use DateTime;
use Ext::Redis::_init;
use Data::Dumper;

my $cmd = shift || '';
if ($cmd eq 'config') {print qq{graph_title Cyclone3 cache usage [SQL] (all hosts)
graph_category cyclone3
graph_vlabel calls
graph_order crt hit
graph_scale no
crt.label cache create / second
crt.draw AREA
crt.min 0
hit.label cache hit / second
hit.draw STACK
hit.min 0
};
	exit 0;
}

my $debug;
	$debug=1 if $cmd eq "debug";

my $datetime_now=DateTime->now('time_zone' => 'local');

my $i;
my $value_crt;
my $value_hit;

for (1..10)
{
	$datetime_now->add('minutes' => -1);
	
	my $date_str=
		sprintf('%04d',$datetime_now->year()).'-'.sprintf('%02d',$datetime_now->month()).'-'.sprintf('%02d',$datetime_now->day())
		.' '
		.sprintf('%02d',$datetime_now->hour()).":".sprintf('%02d',$datetime_now->minute());
	
	my %data=@{$Redis->hgetall('C3|counters|sql_cache|'.$date_str)};
	$value_crt+=$data{'crt'};
	$value_hit+=$data{'hit'};
}

$i=1 unless $i;

print "crt.value " . int(($value_crt/10/60)*100)/100 . "\n";
print "hit.value " . int(($value_hit/10/60)*100)/100 . "\n";

