#!/usr/bin/env perl
# ex:ts=4
BEGIN {
	if (!$ENV{'CYCLONE3PATH'})
	{
		$ENV{'CYCLONE3PATH'}="/www/TOM" if -d "/www/TOM";
		$ENV{'CYCLONE3PATH'}="/Cyclone3" if -d "/Cyclone3";
		$ENV{'CYCLONE3PATH'}="/srv/Cyclone3" if -d "/srv/Cyclone3";
	}
	require $ENV{'CYCLONE3PATH'}."/.bin/c3-init";
}

use strict;
use open ':utf8', ':std';
use if $] < 5.018, 'encoding','utf8';
use utf8;
use DateTime;
use Ext::Redis::_init;
use Data::Dumper;

my $cmd = shift || '';
if ($cmd eq 'config') {print qq{graph_title Cyclone3 cache ratio (all hosts)
graph_category cyclone3
graph_vlabel ratio
graph_order page mdl sql
graph_scale no
page.label page cache ratio
page.min 0
page.draw LINE1
mdl.label module cache ratio
mdl.min 0
mdl.draw LINE1
sql.label sql cache ratio
sql.min 0
sql.draw LINE1
};
	exit 0;
}

my $debug;
	$debug=1 if $cmd eq "debug";

my $datetime_now=DateTime->now('time_zone' => 'local');

my $i;
my %value_crt;
my %value_hit;

for (1..10)
{
	$datetime_now->add('minutes' => -1);
	
	my $date_str=
		sprintf('%04d',$datetime_now->year()).'-'.sprintf('%02d',$datetime_now->month()).'-'.sprintf('%02d',$datetime_now->day())
		.' '
		.sprintf('%02d',$datetime_now->hour()).":".sprintf('%02d',$datetime_now->minute());
	
	my %data=@{$Redis->hgetall('C3|counters|sql|'.$date_str)};
	foreach (grep {$_=~/\|cache_fill$/} keys %data){$value_crt{'sql'}+=$data{$_};}
	foreach (grep {$_=~/\|cache_hit$/} keys %data){$value_hit{'sql'}+=$data{$_};}
#	$value_crt{'sql'}+=$data{'crt'};
#	$value_hit{'sql'}+=$data{'hit'};
	
	my %data=@{$Redis->hgetall('C3|counters|mdl_cache|'.$date_str)};
	$value_crt{'mdl'}+=$data{'crt'};
	$value_hit{'mdl'}+=$data{'hit'};
	
	my %data=@{$Redis->hgetall('C3|counters|page_cache|'.$date_str)};
	$value_crt{'page'}+=$data{'crt'};
	$value_hit{'page'}+=$data{'hit'};
}

$i=1 unless $i;

foreach (sort keys %value_crt)
{
	print "$_.value ".(
		
		int(($value_hit{$_}/($value_crt{$_} || 1))*100)/100
		
	)."\n";
}

