#!/usr/bin/env perl
# ex:ts=4

use strict;
#use warnings;
use Proc::ProcessTable;
use Data::Dumper;

my $cmd = shift || '';
if ($cmd eq 'config') {print qq{graph_title Cyclone3 processes
graph_args --base 1000 -l 0
graph_category cyclone3
graph_order cron job cli pub
graph_vlabel processes
graph_scale no
cron.label cron engine
cron.draw LINE1
job.label job engine
job.draw LINE1
cli.label cli engine
cli.draw LINE1
pub.label pub engine
pub.draw LINE1
total.colour 000000
total.label total
total.draw LINE1
};
	exit 0;
}

my %engines;

my $total_value=0;

my $t = new Proc::ProcessTable;
foreach my $p (@{$t->table})
{
	my $cmd=$p->cmndline;
	next unless $p->{'cmndline'}=~/^c3\-([^ \.]*)/;
	$engines{$1}++;
}

print "cron.value " . ($engines{'cron'} || 0) . "\n";
$total_value+=$engines{'cron'};
print "job.value " . ($engines{'job'} || 0) . "\n";
$total_value+=$engines{'job'};
print "cli.value " . ($engines{'cli'} || 0) . "\n";
$total_value+=$engines{'cli'};
print "pub.value " . ($engines{'pub'} || 0) . "\n";
$total_value+=$engines{'pub'};


print "total.value " . $total_value . "\n";
