#!/usr/bin/env perl
use strict;                   
#use warnings;                 
use LWP;                      
use JSON qw/decode_json/;     

my $host = $ENV{'host'} || 'localhost';

my $ua = LWP::UserAgent->new;
$ua->timeout(10);

sub get_json_from_url {
    my $uri = shift;
    my $res = $ua->get($uri, 'Content-Type' => 'application/json' );
    Carp::confess($res->code . " for " . $uri) unless $res->is_success;
    my $data = do { local $@; eval { decode_json($res->content) } };
    die("Could not decode JSON from: " . $res->content) unless $data;
    return $data;
}

my $data = get_json_from_url("http://$host:9200/_nodes/stats");
#use Data::Dumper;print Dumper($data);
my %out;

foreach my $node (keys %{$data->{nodes}}){
	
	#$out{$data->{'nodes'}->{$node}->{'name'}}=$data->{'nodes'}->{$node}->{'indices'}->{'store'}->{'size_in_bytes'};
	
	$out{'search'}+=$data->{'nodes'}->{$node}->{'indices'}->{'search'}->{'query_total'};
	$out{'indexing'}+=$data->{'nodes'}->{$node}->{'indices'}->{'indexing'}->{'index_total'};
	$out{'get'}+=$data->{'nodes'}->{$node}->{'indices'}->{'get'}->{'total'};
	$out{'refresh'}+=$data->{'nodes'}->{$node}->{'indices'}->{'refresh'}->{'total'};
	
}

if ($ARGV[0] and $ARGV[0] eq 'config')
{
#	print "graph_args --base 1024\n";
	print "graph_title ElasticSearch RLog cluster queries\n";
	print "graph_category elasticsearch_rlog\n";
	print "graph_vlabel queries\n";
	
	print "search.label search\nsearch.type COUNTER\n";
	print "indexing.label indexing\nindexing.type COUNTER\n";
	print "get.label get\nget.type COUNTER\n";
	print "refresh.label refresh\nrefresh.type COUNTER\n";
	
#	foreach my $name (sort keys %out)
#	{
#		print "$name.label $name\n";
#	}
}

elsif (!$ARGV[0] || $ARGV[0] eq 'autoconf')
{
#	foreach my $name (sort keys %out)
#	{
		print "search.value " . $out{'search'} . "\n";
		print "indexing.value " . $out{'indexing'} . "\n";
		print "get.value " . $out{'get'} . "\n";
		print "refresh.value " . $out{'refresh'} . "\n";
#	}
}

exit(0);
