#!/usr/bin/perl
BEGIN {
	if (!$ENV{'CYCLONE3PATH'})
	{
		$ENV{'CYCLONE3PATH'}="/www/TOM" if -d "/www/TOM";
		$ENV{'CYCLONE3PATH'}="/Cyclone3" if -d "/Cyclone3";
		$ENV{'CYCLONE3PATH'}="/srv/Cyclone3" if -d "/srv/Cyclone3";
	}
	require $ENV{'CYCLONE3PATH'}."/.bin/c3-init";
}

my $cmd = shift || '';
if ($cmd eq 'config') {print qq{graph_title Redis expired keys
graph_args --base 1000 -l 0
graph_category cyclone3_redis
graph_order expired evicted
graph_vlabel commands/s
graph_scale no
graph_info This graph monitors the expiration rate
expired.label expired/s
expired.type COUNTER
expired.min 0
evicted.label evicted/s
evicted.type COUNTER
evicted.min 0
};
	exit 0;
}

undef @Ext::Redis::hosts; # don't use sharding
$Redis=Ext::Redis::_connect();

if (!$Redis)
{
	exit 0;
}

my %info=%{$Redis->info()};
print "expired.value " . $info{'expired_keys'} . "\n";
print "evicted.value " . $info{'evicted_keys'} . "\n";
#print "created.value " . ($info{'db0'}=~/keys=(\d+)/)[0] . "\n";