#!/usr/bin/perl
BEGIN {
	if (!$ENV{'CYCLONE3PATH'})
	{
		$ENV{'CYCLONE3PATH'}="/www/TOM" if -d "/www/TOM";
		$ENV{'CYCLONE3PATH'}="/Cyclone3" if -d "/Cyclone3";
		$ENV{'CYCLONE3PATH'}="/srv/Cyclone3" if -d "/srv/Cyclone3";
	}
	require $ENV{'CYCLONE3PATH'}."/.bin/c3-init";
}

my $cmd = shift || '';
if ($cmd eq 'config') {print qq{graph_title Redis memory usage
graph_args --base 1024 -l 0
graph_category cyclone3_redis
graph_order rss used
graph_vlabel memory usage
graph_scale yes
rss.label allocated
rss.draw LINE1
used.label used
used.draw LINE1
};
	exit 0;
}

undef @Ext::Redis::hosts; # don't use sharding
$Redis=Ext::Redis::_connect();

if (!$Redis)
{
	exit 0;
}

my %info=%{$Redis->info()};
use Data::Dumper;
print "rss.value " . $info{'used_memory_rss'} . "\n";
print "used.value " . $info{'used_memory'} . "\n";

