#!/usr/bin/perl
BEGIN {
	if (!$ENV{'CYCLONE3PATH'})
	{
		$ENV{'CYCLONE3PATH'}="/www/TOM" if -d "/www/TOM";
		$ENV{'CYCLONE3PATH'}="/Cyclone3" if -d "/Cyclone3";
		$ENV{'CYCLONE3PATH'}="/srv/Cyclone3" if -d "/srv/Cyclone3";
	}
	require $ENV{'CYCLONE3PATH'}."/.bin/c3-init";
}

my $cmd = shift || '';
if ($cmd eq 'config') {print qq{graph_title Redis changes since last save
graph_args --base 1000 -l 0
graph_category cyclone3_redis
graph_order keys
graph_vlabel changed keys
graph_scale yes
graph_info This graph monitors the number of keys changed since last save
keys.label keys
keys.draw AREA
keys.min 0
};
	exit 0;
}

undef @Ext::Redis::hosts; # don't use sharding
$Redis=Ext::Redis::_connect();

if (!$Redis)
{
	exit 0;
}

my %info=%{$Redis->info()};
print "keys.value " . $info{'changes_since_last_save'} . "\n";